### ISSUE TITLE
additional header

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#154]
hey gang,

can someone show me how i can put a DateTime into the additionalHeader? I'd like to send some additiona ldata with stateless requests?

**Comment by jpfr** [comment]
> Reserved for future use.
Applications that do not understand the header should ignore it

I guess you can put whatever you want into the additionalHeader (encoded as an extensionobject).
Applications will just ignore it.

Otherwise, UA_ResponseHeader already contains a ```datetime``` field.
For reads, UA_ReadResponse returns a UA_DataValue for every read. There you can also put timestamp information down to picosecond precision.

**Comment by Stasik0** [comment]
Yea, i need a second timestamp... Searching for a code snipplet :)
