### ISSUE TITLE
Cannot read ServerStatus

### ISSUE THREAD

**Issue by Stasik0** [acplt/open62541#182]
Seems to be an another regression: while trying to click on Objects->Server->ServerStatus I get `Read attributes of node 'NS0|Numeric|2256' failed [ret = BadNotFound].`
I am sure it was working the other day since node is populated in ua_server.c

**Comment by Stasik0** [comment]
@jpfr i have found the problem, while encoding the extension object in the variant, we take nodeid
```
ServerStatusDataType,862,DataType
```
however, UaExpert expects
```
ServerStatusDataType_Encoding_DefaultBinary,864,Object
```
i dirty workarounded an exception for 862 in source, however this is *not a fix*, unfortunately i fail to see, in what cases we need to add +2 and in which we do not have to :( (probably i need to RTFS, but have no standard at hand)

**Comment by jpfr** [comment]
That's a good question.

I was under the impression that the nodeid in an extensionobject would always be the "normal" nodeid since binary encoding is triggered by the encoding byte.
![image](https://cloud.githubusercontent.com/assets/1726411/6431729/c22d6fa2-c039-11e4-8f03-a3846401ea4d.png)

Is it correct that we encode ServerStatusDataType_Encoding_DefaultBinary = 864 **and** set the encoding byte to binary?

**Comment by Stasik0** [comment]
this is the current *working* version

![uaexpert](https://cloud.githubusercontent.com/assets/469170/6431775/de99f500-c03b-11e4-9f2d-a89dc7b2f666.png)

**Comment by Stasik0** [comment]
it seems that ```StructuredType``` structs are affected, probably we need to store this info in ```UA_DataType``` and evaluate in ```*_encodeBinary``` accordingly, or do you have it already?
