### ISSUE TITLE
Problem: Create libopen62541 for QNX real-time OS

### ISSUE THREAD

**Issue by kadomcev** [acplt/open62541#197]
Problem: How create libopen62541 for QNX ?

**Comment by jpfr** [comment]
Set the right compiler in cmake.

A random google search brought this file:
https://www.mail-archive.com/cmake@cmake.org/msg24398/Toolchain-qnx-640-armle.cmake

And this command to run cmake with it.
cmake -DCMAKE_TOOLCHAIN_FILE=c:\Toolchain-qnx-640-armle.cmake

But since there are a lot of differences between embedded systems, better consult your own documenation.

**Comment by kadomcev** [comment]
Problem solved for QNX.
I compile the project for QNX.
I confirm open62541 works in QNX !))

**Comment by Stasik0** [comment]
nice! Some special tweaks or just normally compiled?

**Comment by kadomcev** [comment]
all the sources compiled in QNX Momentics IDE 4.7 (-std=c99 conflict with libraries IDE, so i correct code to standart c)

**Comment by Stasik0** [comment]
I added QNX to open62541.org
