### ISSUE TITLE
Ship only static binaries

### ISSUE THREAD

**Issue by jpfr** [acplt/open62541#379]
Currently there is little use for shared libraries.
I guess everybody wants a binary that just works and can be easily copied.

As requested by @Stasik0, the function-specific examples are now built statically.
Can we make the change for all examples and the binaries we ship in the releases?

Of course, we can still put the .dll / .so into the release-zip, even if the binaries are static...

**Comment by Stasik0** [comment]
Well, there are already server_static and client_static

**Comment by jpfr** [comment]
Yeah. Eventually, we should break up the big examples into per-feature examples.
So we end up with only the static binaries from the /examples directory.

Then we can just omit the _static postfix.

**Comment by ichrispa** [comment]
The dynamic linked libraries are imho important when creating multi-server/multi-client applications which all run on the same stack code base; I did use them extensively in the past to ensure a consistent codebase in these scenarios.

I would also like to keep the big-mess examples, because they are rather good for testing/coverage (i.e. the "has it all" binary can be run for testing). Though I would not necessarily call them "examples" in this case?
