### ISSUE TITLE
Problem with non RTC

### ISSUE THREAD

**Issue by NetoLe** [acplt/open62541#472]
Hello, I think this is more a minor issue, but I want to tell you that.

We try to implement an open62541-Server on an embedded device (and it works fine so far), which has no RTC.
That means it starts with a date 1.1.1970. It synchronizes when it gets connected to a PC, which causes to change the date by 45 years. That knocks out the server-application. Maybe this is a part that should be done in the future for embedded devices. We got it to work, commenting this part out (at ua_server.c):

  `  // UA_Job cleanup = {.type = UA_JOBTYPE_METHODCALL,
                      // .job.methodCall = {.method = UA_Server_cleanup, .data = NULL} };
    // UA_Server_addRepeatedJob(server, cleanup, 10000, NULL); `

We are not using the latest stable build because we want to use method calls (which are working fine) and the UA_Int..-casts on the byte-arrays in the decoder and encoder-parts caused the system to crash all the time, when reading casted 0xFF-Values on the first Byte (working on a 32-bit ARM); we implemented a shifting-operation, which we then saw in the latest-git-Version, which we are using now.

**Comment by Stasik0** [comment]
Hi,

commenting server cleanup will maybe temporaliy fix your issue, but
probably cause some ressource leaks, since the server will never cleanup
the expired sessions and secure channels.
Could you please trace which line of the scheduler knocks the server out?
Actually it should be a good idea to fix it.

The second issue is probably the unaligned access. Did you try undefined
this variable manually
https://github.com/acplt/open62541/blob/9dd20578a6333e33f21a2c6e85c48b3e50c30f6c/include/ua_config.h.in#L69
?

Best Regards
